CENTROID:
  IS_VIDEO_INPUT: False

  DISTANCE_TOLERANCE: 140
  VERTICAL_TOLERANCE: 20

  MAX_DISAPPEARED: 50

  IGNORE_REGISTRATION_ZONES: False

  LANE_SEPARATOR: 1000

  DEREGISTRATION_ZONE: 750

  FRAME_WIDTH: 11520