DEEPSORT:
  REID_CKPT: "../weights/tracker/deepsort/feature_extractor.t7"
  MAX_DIST: 0.4
  MIN_CONFIDENCE: 0.4
  NMS_MAX_OVERLAP: 0.7
  MAX_IOU_DISTANCE: 0.65
  MAX_AGE: 70
  N_INIT: 5
  NN_BUDGET: 10000
  MAX_ID: 100000

