DEEPSORT:
  REID_CKPT: "../weights/tracker/deepsort/feature_extractor.t7"
  MAX_DIST: 0.7
  MIN_CONFIDENCE: 0.4
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.75
  MAX_AGE: 10
  N_INIT: 6
  NN_BUDGET: 10000
  MAX_ID: 100000

