name: Documentation Generator

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        poetry-version: [1.1.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry-version
        run: poetry --version

      - name: Install requirements and activate Venv
        run: poetry shell

      - name: Generate documentation with pdoc3
        run: pdoc --html pancake --html-dir docs --force
      